FROM image-registry.openshift-image-registry.svc:5000/openshift/tools:latest

#Install crane,rekor,cosign and roxctl
RUN  wget https://github.com/google/go-containerregistry/releases/download/v0.11.0/go-containerregistry_Linux_x86_64.tar.gz \
     && tar xvf go-containerregistry_Linux_x86_64.tar.gz -C /usr/local/bin/ \
     && rm -rf go-containerregistry_Linux_x86_64.tar.gz /usr/local/bin/gcrane /usr/local/bin/README.md /usr/local/bin/LICENSE

CMD ["/usr/local/bin/crane"]
