FROM image-registry.openshift-image-registry.svc:5000/openshift/tools:latest

#Install roxctl
RUN  curl -o /usr/local/bin/roxctl https://mirror.openshift.com/pub/rhacs/assets/latest/bin/linux/roxctl \
     && chmod +x /usr/local/bin/roxctl

ENTRYPOINT ["/usr/local/bin/roxctl"]
