#This image is provisioned through a buildah task in tekton using an imagestream (below) that exists 
#in-cluster. There currently is no official red hat image for crane, cosign and rekor.
FROM image-registry.openshift-image-registry.svc:5000/openshift/tools:latest

#Install crane,rekor,cosign and roxctl
RUN  wget https://github.com/google/go-containerregistry/releases/download/v0.11.0/go-containerregistry_Linux_x86_64.tar.gz \
     && tar xvf go-containerregistry_Linux_x86_64.tar.gz -C /usr/local/bin/ \
     && rm -rf go-containerregistry_Linux_x86_64.tar.gz /usr/local/bin/gcrane /usr/local/bin/README.md /usr/local/bin/LICENSE \
     && dnf install -y https://github.com/sigstore/cosign/releases/download/v1.10.0/cosign-1.10.0.x86_64.rpm \
     && dnf clean all \
     && wget -O /usr/local/bin/rekor https://github.com/sigstore/rekor/releases/download/v0.10.0/rekor-cli-linux-amd64 \
     && chmod +x /usr/local/bin/rekor \
     && wget -O /usr/bin/roxctl https://mirror.openshift.com/pub/rhacs/assets/latest/bin/linux/roxctl \
     && chmod +x /usr/bin/roxctl

#Leaving default command as roxctl as it should be the most widely used.
CMD ["/usr/bin/roxctl"]
